# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b59293e37a4038840d5ca55220de834741575a337f28c2df4ce26305563a88187744de874f5a21c58d0d5bc2bf9eef934db94045b8a979f52ab5c2151fa311bd

test:
  secret_key_base: c9cd96d4991ed3a93da1a2862e96518ef63880c6f899ff5ecb967c504cebad6b82d12c50903cb1de998dccfd0edc56ea667516c534ba0e18d7029bfda88bfb01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
